name: FairAnvil
version: '${project.version}'
main: com.scorp.fairanvil.FairAnvil
api-version: 1.17
authors: [ Scorp ]
description: Anvils use experience points not levels

commands:
  fairanvils:
    description: allows you to toggle fairanvils
    usage: /<command>
    permission: fairanvils.toggle

permissions:
  fairanvils.toggle:
    description: allows you to use fairanvil command
    default: op